-- =================================================================
-- DATABASE RBAC SETUP SCRIPT FOR FIELD MAPPER
-- =================================================================
-- This script creates a 3-tier role hierarchy for database access control
-- 
-- Role Hierarchy:
--   <DBNAME>_ADMIN (Full administrative access)
--       ↓ inherits
--   <DBNAME>_READWRITE (Read and write access)
--       ↓ inherits
--   <DBNAME>_READONLY (Read-only access)
-- 
-- Variables to replace:
--   {{DATABASE}} - Database name from deploy.config
--   {{SCHEMA}} - Schema name from deploy.config
--   {{CURRENT_USER}} - Current Snowflake user to assign admin role
-- =================================================================

-- =================================================================
-- SECTION 1: Create Role Hierarchy (Use SECURITYADMIN)
-- =================================================================

USE ROLE SECURITYADMIN;

-- Create roles
CREATE ROLE IF NOT EXISTS {{DATABASE}}_ADMIN;
CREATE ROLE IF NOT EXISTS {{DATABASE}}_READWRITE;
CREATE ROLE IF NOT EXISTS {{DATABASE}}_READONLY;

-- Add comments to roles
ALTER ROLE {{DATABASE}}_ADMIN SET COMMENT = 'Administrator role for {{DATABASE}} database';
ALTER ROLE {{DATABASE}}_READWRITE SET COMMENT = 'Read-Write role for {{DATABASE}} database';
ALTER ROLE {{DATABASE}}_READONLY SET COMMENT = 'Read-Only role for {{DATABASE}} database';

-- Establish role hierarchy (READONLY -> READWRITE -> ADMIN)
GRANT ROLE {{DATABASE}}_READONLY TO ROLE {{DATABASE}}_READWRITE;
GRANT ROLE {{DATABASE}}_READWRITE TO ROLE {{DATABASE}}_ADMIN;

-- Grant Admin role to SYSADMIN for management
GRANT ROLE {{DATABASE}}_ADMIN TO ROLE SYSADMIN;

-- Assign current user to Admin role
GRANT ROLE {{DATABASE}}_ADMIN TO USER {{CURRENT_USER}};

-- =================================================================
-- SECTION 2: Create Database and Schema (Use SYSADMIN)
-- =================================================================

USE ROLE SYSADMIN;

-- Create database
CREATE DATABASE IF NOT EXISTS {{DATABASE}};
USE DATABASE {{DATABASE}};

-- Create schema
CREATE SCHEMA IF NOT EXISTS {{SCHEMA}};

-- =================================================================
-- SECTION 3: Grant Privileges BEFORE Ownership Transfer
-- =================================================================

-- Grant database and schema usage to lower roles
GRANT USAGE ON DATABASE {{DATABASE}} TO ROLE {{DATABASE}}_READONLY;
GRANT USAGE ON DATABASE {{DATABASE}} TO ROLE {{DATABASE}}_READWRITE;
GRANT USAGE ON DATABASE {{DATABASE}} TO ROLE {{DATABASE}}_ADMIN;
GRANT USAGE ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READONLY;
GRANT USAGE ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READWRITE;
GRANT USAGE ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;

-- =================================================================
-- SECTION 4: Grant ReadOnly Privileges
-- =================================================================

-- SELECT on all existing and future tables and views
GRANT SELECT ON ALL TABLES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READONLY;
GRANT SELECT ON ALL VIEWS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READONLY;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READONLY;

GRANT SELECT ON FUTURE TABLES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READONLY;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READONLY;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READONLY;

-- USAGE on functions and procedures
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READONLY;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READONLY;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READONLY;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READONLY;

-- READ on stages
GRANT READ ON ALL STAGES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READONLY;
GRANT READ ON FUTURE STAGES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READONLY;

-- USAGE on file formats
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READONLY;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READONLY;

-- MONITOR on tasks and SELECT on streams
GRANT MONITOR ON ALL TASKS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READONLY;
GRANT MONITOR ON FUTURE TASKS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READONLY;
GRANT SELECT ON ALL STREAMS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READONLY;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READONLY;

-- =================================================================
-- SECTION 5: Grant ReadWrite Privileges
-- =================================================================

-- DML on all existing and future tables
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READWRITE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READWRITE;

-- READ and WRITE on stages
GRANT READ, WRITE ON ALL STAGES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READWRITE;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READWRITE;

-- CREATE privileges on schema
GRANT CREATE TABLE ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READWRITE;
GRANT CREATE VIEW ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READWRITE;
GRANT CREATE STAGE ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READWRITE;
GRANT CREATE FILE FORMAT ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READWRITE;
GRANT CREATE SEQUENCE ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READWRITE;
GRANT CREATE FUNCTION ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READWRITE;
GRANT CREATE PROCEDURE ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READWRITE;

-- OPERATE on tasks
GRANT OPERATE ON ALL TASKS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READWRITE;
GRANT OPERATE ON FUTURE TASKS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_READWRITE;

-- =================================================================
-- SECTION 6: Grant Admin Privileges
-- =================================================================

-- CREATE SCHEMA privilege
GRANT CREATE SCHEMA ON DATABASE {{DATABASE}} TO ROLE {{DATABASE}}_ADMIN;

-- ALL PRIVILEGES on schema
GRANT ALL PRIVILEGES ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;

-- ALL PRIVILEGES on all existing objects
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;
GRANT ALL PRIVILEGES ON ALL MATERIALIZED VIEWS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;
GRANT ALL PRIVILEGES ON ALL STAGES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;
GRANT ALL PRIVILEGES ON ALL FILE FORMATS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;
GRANT ALL PRIVILEGES ON ALL STREAMS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;
GRANT ALL PRIVILEGES ON ALL TASKS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;

-- ALL PRIVILEGES on all future objects
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE MATERIALIZED VIEWS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE FUNCTIONS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE STREAMS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE TASKS IN SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN;

-- Database management privileges for admin
GRANT MODIFY, MONITOR ON DATABASE {{DATABASE}} TO ROLE {{DATABASE}}_ADMIN;

-- =================================================================
-- SECTION 7: Warehouse Access
-- =================================================================

-- Grant warehouse usage to all roles
GRANT USAGE ON WAREHOUSE {{WAREHOUSE}} TO ROLE {{DATABASE}}_READONLY;
GRANT USAGE ON WAREHOUSE {{WAREHOUSE}} TO ROLE {{DATABASE}}_READWRITE;
GRANT USAGE ON WAREHOUSE {{WAREHOUSE}} TO ROLE {{DATABASE}}_ADMIN;

-- =================================================================
-- SECTION 8: Transfer Ownership (LAST STEP)
-- =================================================================
-- Note: Ownership transfer is done last to ensure all grants complete
-- SYSADMIN retains access via the role hierarchy (ADMIN -> SYSADMIN)

GRANT OWNERSHIP ON DATABASE {{DATABASE}} TO ROLE {{DATABASE}}_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{DATABASE}}_ADMIN COPY CURRENT GRANTS;

-- =================================================================
-- SETUP COMPLETE
-- =================================================================

SELECT 
    '✓ RBAC Setup Complete!' as STATUS,
    '{{DATABASE}}' as DATABASE_NAME,
    '{{DATABASE}}_READONLY' as READONLY_ROLE,
    '{{DATABASE}}_READWRITE' as READWRITE_ROLE,
    '{{DATABASE}}_ADMIN' as ADMIN_ROLE,
    '{{CURRENT_USER}}' as ADMIN_USER;
